<?php

namespace Tests\Feature\Modules\Billing\Http\Controllers;

use Tests\TestCase;

/**
 * @see \Modules\Billing\Http\Controllers\PaypalController
 */
class PaypalControllerTest extends TestCase
{
    /**
     * @test
     */
    public function cancel_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('payment.cancel'));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function payment_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('payment'));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function success_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('payment.success'));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
