<?php

namespace Tests\Feature\Modules\Billing\Http\Controllers;

use Tests\TestCase;

/**
 * @see \Modules\Billing\Http\Controllers\WishlistController
 */
class WishlistControllerTest extends TestCase
{
    /**
     * @test
     */
    public function wishlist_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('add-to-wishlist', ['slug' => $slug]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function wishlist_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \Modules\Billing\Http\Controllers\WishlistController::class,
            'wishlist',
            \Modules\Billing\Http\Requests\Store::class
        );
    }

    /**
     * @test
     */
    public function wishlist_delete_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('wishlist-delete', ['id' => $id]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
