<?php

namespace Tests\Feature\Modules\Category\Http\Controllers;

use Tests\TestCase;

/**
 * @see \Modules\Category\Http\Controllers\CategoryController
 */
class CategoryControllerTest extends TestCase
{
    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('categories.create'));

        $response->assertOk();
        $response->assertViewIs('category::create');
        $response->assertViewHas('categories');
        $response->assertViewHas('category');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->delete(route('categories.destroy', ['category' => $category]));

        $response->assertRedirect(route('categories.index'));
        $this->assertModelMissing($category);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('categories.edit', ['category' => $category]));

        $response->assertOk();
        $response->assertViewIs('category::edit');
        $response->assertViewHas('category');
        $response->assertViewHas('categories');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('categories.index'));

        $response->assertRedirect(route('categories.create'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('categories.store'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('categories.index'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \Modules\Category\Http\Controllers\CategoryController::class,
            'store',
            \Modules\Category\Http\Requests\Api\Store::class
        );
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->put(route('categories.update', ['category' => $category]), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \Modules\Category\Http\Controllers\CategoryController::class,
            'update',
            \Modules\Category\Http\Requests\Api\Update::class
        );
    }

    // test cases...
}
