<?php

declare(strict_types=1);

namespace Tests\Unit\Actions\Front;

use Modules\Front\Actions\NewsletterVerifyAction;
use Modules\Newsletter\Models\Newsletter;
use Tests\Unit\Actions\ActionTestCase;

class NewsletterVerifyActionTest extends ActionTestCase
{
    public function test_invoke_validates_newsletter_by_token(): void
    {
        // Arrange - Create newsletter (token will be auto-generated by observer)
        $newsletter = new Newsletter([
            'email' => 'test@example.com',
            'is_validated' => false,
        ]);
        $newsletter->save();
        
        // Get the auto-generated token
        $token = $newsletter->token;
        
        $action = new NewsletterVerifyAction();

        // Act
        $result = $action($token);

        // Assert
        $this->assertTrue($result);
        $newsletter->refresh();
        $this->assertEquals(1, $newsletter->is_validated);
    }

    public function test_invoke_returns_false_for_invalid_token(): void
    {
        // Arrange
        $action = new NewsletterVerifyAction();

        // Act
        $result = $action('invalid-token');

        // Assert
        $this->assertFalse($result);
    }

    public function test_invoke_returns_false_for_nonexistent_token(): void
    {
        // Arrange
        $newsletter = new Newsletter([
            'email' => 'existing@example.com',
        ]);
        $newsletter->save();
        
        $action = new NewsletterVerifyAction();

        // Act
        $result = $action('nonexistent-token');

        // Assert
        $this->assertFalse($result);
    }

    public function test_invoke_only_validates_matching_token(): void
    {
        // Arrange
        $newsletter1 = new Newsletter([
            'email' => 'first@example.com',
            'is_validated' => false,
        ]);
        $newsletter1->save();
        $token1 = $newsletter1->token;
        
        $newsletter2 = new Newsletter([
            'email' => 'second@example.com',
            'is_validated' => false,
        ]);
        $newsletter2->save();

        $action = new NewsletterVerifyAction();

        // Act
        $action($token1);

        // Assert
        $newsletter1->refresh();
        $newsletter2->refresh();
        $this->assertEquals(1, $newsletter1->is_validated);
        $this->assertEquals(0, $newsletter2->is_validated);
    }

    public function test_invoke_saves_to_database(): void
    {
        // Arrange
        $newsletter = new Newsletter([
            'email' => 'test@example.com',
            'is_validated' => false,
        ]);
        $newsletter->save();
        $token = $newsletter->token;
        
        $action = new NewsletterVerifyAction();

        // Act
        $action($token);

        // Assert
        $this->assertDatabaseHas('newsletters', [
            'id' => $newsletter->id,
            'is_validated' => 1,
        ]);
    }
}
