<?php

declare(strict_types=1);

namespace Tests\Unit\Actions\Front;

use Modules\Front\Actions\NewsletterDeleteAction;
use Modules\Newsletter\Models\Newsletter;
use Tests\Unit\Actions\ActionTestCase;

class NewsletterDeleteActionTest extends ActionTestCase
{
    public function test_invoke_deletes_newsletter_by_token(): void
    {
        // Arrange - Create newsletter (token will be auto-generated by observer)
        $newsletter = new Newsletter([
            'email' => 'test@example.com',
        ]);
        $newsletter->save();
        $token = $newsletter->token;
        
        $action = new NewsletterDeleteAction();

        // Act
        $result = $action($token);

        // Assert
        $this->assertTrue($result);
        $this->assertDatabaseMissing('newsletters', [
            'id' => $newsletter->id,
        ]);
    }

    public function test_invoke_returns_false_for_invalid_token(): void
    {
        // Arrange
        $action = new NewsletterDeleteAction();

        // Act
        $result = $action('invalid-token');

        // Assert
        $this->assertFalse($result);
    }

    public function test_invoke_returns_false_for_nonexistent_token(): void
    {
        // Arrange
        $newsletter = new Newsletter([
            'email' => 'existing@example.com',
        ]);
        $newsletter->save();
        
        $action = new NewsletterDeleteAction();

        // Act
        $result = $action('nonexistent-token');

        // Assert
        $this->assertFalse($result);
    }

    public function test_invoke_only_deletes_matching_token(): void
    {
        // Arrange
        $newsletter1 = new Newsletter([
            'email' => 'first@example.com',
        ]);
        $newsletter1->save();
        $token1 = $newsletter1->token;
        
        $newsletter2 = new Newsletter([
            'email' => 'second@example.com',
        ]);
        $newsletter2->save();

        $action = new NewsletterDeleteAction();

        // Act
        $action($token1);

        // Assert
        $this->assertDatabaseMissing('newsletters', ['id' => $newsletter1->id]);
        $this->assertDatabaseHas('newsletters', ['id' => $newsletter2->id]);
    }

    public function test_invoke_handles_empty_token(): void
    {
        // Arrange
        $action = new NewsletterDeleteAction();

        // Act
        $result = $action('');

        // Assert
        $this->assertFalse($result);
    }
}
