<?php

declare(strict_types=1);

namespace Tests\Unit\Actions\Newsletter;

use Modules\Newsletter\Actions\CreateNewsletterAction;
use Modules\Newsletter\DTOs\NewsletterDTO;
use Modules\Newsletter\Models\Newsletter;
use Modules\Newsletter\Repository\NewsletterRepository;
use Tests\Unit\Actions\ActionTestCase;

class CreateNewsletterActionTest extends ActionTestCase
{
    public function test_execute_creates_newsletter_with_dto(): void
    {
        // Arrange
        $repository = new NewsletterRepository();
        $action = new CreateNewsletterAction($repository);

        $dto = new NewsletterDTO(
            id: null,
            email: 'test@example.com',
            token: 'test-token-123',
            is_validated: true,
        );

        // Act
        $result = $action->execute($dto);

        // Assert
        $this->assertInstanceOf(Newsletter::class, $result);
        $this->assertEquals('test@example.com', $result->email);
        // Token is auto-generated by NewsletterObserver
        $this->assertNotNull($result->token);
        $this->assertEquals(64, strlen($result->token));
        $this->assertTrue($result->is_validated);
        $this->assertDatabaseHas('newsletters', [
            'email' => 'test@example.com',
            'is_validated' => true,
        ]);
    }

    public function test_execute_creates_unvalidated_newsletter(): void
    {
        // Arrange
        $repository = new NewsletterRepository();
        $action = new CreateNewsletterAction($repository);

        $dto = new NewsletterDTO(
            id: null,
            email: 'unvalidated@example.com',
            token: 'unvalidated-token',
            is_validated: false,
        );

        // Act
        $result = $action->execute($dto);

        // Assert
        $this->assertInstanceOf(Newsletter::class, $result);
        $this->assertEquals('unvalidated@example.com', $result->email);
        $this->assertFalse($result->is_validated);
        $this->assertDatabaseHas('newsletters', [
            'email' => 'unvalidated@example.com',
            'is_validated' => false,
        ]);
    }

    public function test_execute_creates_newsletter_from_array(): void
    {
        // Arrange
        $repository = new NewsletterRepository();
        $action = new CreateNewsletterAction($repository);

        $dto = NewsletterDTO::fromArray([
            'email' => 'fromarray@example.com',
            'token' => 'array-token',
            'is_validated' => true,
        ]);

        // Act
        $result = $action->execute($dto);

        // Assert
        $this->assertInstanceOf(Newsletter::class, $result);
        $this->assertEquals('fromarray@example.com', $result->email);
        // Token is auto-generated by NewsletterObserver
        $this->assertNotNull($result->token);
        $this->assertEquals(64, strlen($result->token));
        $this->assertTrue($result->is_validated);
    }

    public function test_execute_creates_newsletter_with_auto_generated_token(): void
    {
        // Arrange
        $repository = new NewsletterRepository();
        $action = new CreateNewsletterAction($repository);

        $dto = new NewsletterDTO(
            id: null,
            email: 'autotoken@example.com',
            token: null,
            is_validated: true,
        );

        // Act
        $result = $action->execute($dto);

        // Assert
        $this->assertInstanceOf(Newsletter::class, $result);
        $this->assertEquals('autotoken@example.com', $result->email);
        // Token is auto-generated by NewsletterObserver when null
        $this->assertNotNull($result->token);
        $this->assertEquals(64, strlen($result->token));
        $this->assertDatabaseHas('newsletters', [
            'email' => 'autotoken@example.com',
        ]);
    }

    public function test_execute_creates_newsletter_with_unique_emails(): void
    {
        // Arrange
        $repository = new NewsletterRepository();
        $action = new CreateNewsletterAction($repository);

        $dto1 = new NewsletterDTO(
            id: null,
            email: 'unique1@example.com',
            token: 'token1',
            is_validated: true,
        );

        $dto2 = new NewsletterDTO(
            id: null,
            email: 'unique2@example.com',
            token: 'token2',
            is_validated: false,
        );

        // Act
        $result1 = $action->execute($dto1);
        $result2 = $action->execute($dto2);

        // Assert
        $this->assertEquals('unique1@example.com', $result1->email);
        $this->assertEquals('unique2@example.com', $result2->email);
        $this->assertEquals(2, Newsletter::count());
    }
}
