<?php

declare(strict_types=1);

namespace Tests\Unit\Actions\Newsletter;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Modules\Newsletter\Actions\FindNewsletterAction;
use Modules\Newsletter\Models\Newsletter;
use Modules\Newsletter\Repository\NewsletterRepository;
use Tests\Unit\Actions\ActionTestCase;

class FindNewsletterActionTest extends ActionTestCase
{
    public function test_execute_finds_newsletter_by_id(): void
    {
        // Arrange
        $newsletter = Newsletter::factory()->create([
            'email' => 'find@example.com',
            'is_validated' => true,
        ]);

        $repository = new NewsletterRepository();
        $action = new FindNewsletterAction($repository);

        // Act
        $result = $action->execute($newsletter->id);

        // Assert
        $this->assertInstanceOf(Model::class, $result);
        $this->assertInstanceOf(Newsletter::class, $result);
        $this->assertEquals($newsletter->id, $result->id);
        $this->assertEquals('find@example.com', $result->email);
        $this->assertTrue($result->is_validated);
    }

    public function test_execute_finds_newsletter_with_all_attributes(): void
    {
        // Arrange
        $newsletter = Newsletter::factory()->create([
            'email' => 'complete@example.com',
            'is_validated' => true,
        ]);

        $repository = new NewsletterRepository();
        $action = new FindNewsletterAction($repository);

        // Act
        $result = $action->execute($newsletter->id);

        // Assert
        $this->assertEquals($newsletter->id, $result->id);
        $this->assertEquals('complete@example.com', $result->email);
        // Token is auto-generated by NewsletterObserver
        $this->assertNotNull($result->token);
        $this->assertEquals(64, strlen($result->token));
        $this->assertTrue($result->is_validated);
    }

    public function test_execute_throws_exception_for_nonexistent_newsletter(): void
    {
        // Arrange
        $repository = new NewsletterRepository();
        $action = new FindNewsletterAction($repository);

        // Assert & Act
        $this->expectException(ModelNotFoundException::class);
        $action->execute(999999);
    }

    public function test_execute_finds_unvalidated_newsletter(): void
    {
        // Arrange
        $newsletter = Newsletter::factory()->create([
            'email' => 'unvalidated@example.com',
            'is_validated' => false,
        ]);

        $repository = new NewsletterRepository();
        $action = new FindNewsletterAction($repository);

        // Act
        $result = $action->execute($newsletter->id);

        // Assert
        $this->assertInstanceOf(Newsletter::class, $result);
        $this->assertEquals('unvalidated@example.com', $result->email);
        $this->assertFalse($result->is_validated);
    }
}
