<?php

namespace Tests\Feature\Modules\Admin\Http\Controllers;

use Tests\TestCase;

/**
 * @see \Modules\Admin\Http\Controllers\AdminController
 */
class AdminControllerTest extends TestCase
{
    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('admin'));

        $response->assertOk();
        $response->assertViewIs('admin::index');
        $response->assertViewHas('users');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function message_five_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('messages.five'));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
