<?php

namespace Tests\Feature\Modules\Settings\Http\Controllers;

use Tests\TestCase;

/**
 * @see \Modules\Settings\Http\Controllers\SettingsController
 */
class SettingsControllerTest extends TestCase
{
    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('settings.index'));

        $response->assertOk();
        $response->assertViewIs('settings::edit');
        $response->assertViewHas('settings');

        // TODO: perform additional assertions
    }

    // test cases...
}
