<?php

namespace Tests\Feature\Modules\Product\Http\Controllers;

use Tests\TestCase;

/**
 * @see \Modules\Product\Http\Controllers\ProductReviewController
 */
class ProductReviewControllerTest extends TestCase
{
    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->delete(route('product_review.destroy', ['product_review' => $product_review]));

        $response->assertRedirect(route('review.index'));
        $this->assertModelMissing($productReview);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('product_review.edit', ['product_review' => $product_review]));

        $response->assertOk();
        $response->assertViewIs('product::review.edit');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('product_review.index'));

        $response->assertOk();
        $response->assertViewIs('product::review.index');
        $response->assertViewHas('reviews');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('product.review.store', ['slug' => $slug]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(back());

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \Modules\Product\Http\Controllers\ProductReviewController::class,
            'store',
            \Modules\Product\Http\Requests\ProductReviewStore::class
        );
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->put(route('product_review.update', ['product_review' => $product_review]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('product::review.index'));

        // TODO: perform additional assertions
    }

    // test cases...
}
