<?php

namespace Tests\Feature\Modules\Billing\Http\Controllers\Api;

use Tests\TestCase;

/**
 * @see \Modules\Billing\Http\Controllers\Api\StripeController
 */
class StripeControllerTest extends TestCase
{
    /**
     * @test
     */
    public function stripe_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post('api/v1/stripe', [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function stripe_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \Modules\Billing\Http\Controllers\Api\StripeController::class,
            'stripe',
            \Modules\Billing\Http\Requests\Api\Stripe::class
        );
    }

    // test cases...
}
