<?php

namespace Tests\Unit\Http\Requests\Password;

use Tests\TestCase;

/**
 * @see \App\Http\Requests\Password\Store
 */
class StoreTest extends TestCase
{
    /** @var \App\Http\Requests\Password\Store */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\Password\Store();
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'current_password' => [
                'required',
            ],
            'new_password' => [
                'required',
            ],
            'new_confirm_password' => [
                'same:new_password',
            ],
        ], $actual);
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    // test cases...
}
