<?php

namespace Tests\Feature\Modules\Coupon\Http\Controllers;

use Tests\TestCase;

/**
 * @see \Modules\Coupon\Http\Controllers\CouponController
 */
class CouponControllerTest extends TestCase
{
    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('coupons.create'));

        $response->assertOk();
        $response->assertViewIs('coupon::create');
        $response->assertViewHas('coupon');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->delete(route('coupons.destroy', ['coupon' => $coupon]));

        $response->assertRedirect(back());
        $this->assertModelMissing($coupon);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('coupons.edit', ['coupon' => $coupon]));

        $response->assertOk();
        $response->assertViewIs('coupon::edit');
        $response->assertViewHas('coupon');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('coupons.index'));

        $response->assertOk();
        $response->assertViewIs('coupon::index');
        $response->assertViewHas('coupons');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('coupons.store'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('coupons.index'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \Modules\Coupon\Http\Controllers\CouponController::class,
            'store',
            \Modules\Coupon\Http\Requests\Store::class
        );
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->put(route('coupons.update', ['coupon' => $coupon]), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \Modules\Coupon\Http\Controllers\CouponController::class,
            'update',
            \Modules\Coupon\Http\Requests\Update::class
        );
    }

    // test cases...
}
