<?php

namespace Tests\Feature\Modules\Banner\Http\Controllers;

use Tests\TestCase;

/**
 * @see \Modules\Banner\Http\Controllers\BannerController
 */
class BannerControllerTest extends TestCase
{
    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('banners.create'));

        $response->assertOk();
        $response->assertViewIs('banner::create');
        $response->assertViewHas('banner');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->delete(route('banners.destroy', ['banner' => $banner]));

        $response->assertRedirect(route('banners.index'));
        $this->assertModelMissing($banner);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('banners.edit', ['banner' => $banner]));

        $response->assertOk();
        $response->assertViewIs('banner::edit');
        $response->assertViewHas('banner');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('banners.index'));

        $response->assertOk();
        $response->assertViewIs('banner::index');
        $response->assertViewHas('banners');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('banners.store'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('banners.index'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \Modules\Banner\Http\Controllers\BannerController::class,
            'store',
            \Modules\Banner\Http\Requests\Store::class
        );
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->put(route('banners.update', ['banner' => $banner]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('banners.edit', $banner));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \Modules\Banner\Http\Controllers\BannerController::class,
            'update',
            \Modules\Banner\Http\Requests\Update::class
        );
    }

    // test cases...
}
