<?php

namespace Tests\Feature\Modules\Front\Http\Controllers;

use Tests\TestCase;

/**
 * @see \Modules\Front\Http\Controllers\FrontController
 */
class FrontControllerTest extends TestCase
{
    /**
     * @test
     */
    public function about_us_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('about-us'));

        $response->assertOk();
        $response->assertViewIs('front::pages.about-us');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function blog_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('blog'));

        $response->assertOk();
        $response->assertViewIs('front::pages.blog');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function blog_by_category_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('blog.category', ['slug' => $slug]));

        $response->assertOk();
        $response->assertViewIs('front::pages.blog');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function blog_by_tag_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('blog.tag', ['slug' => $slug]));

        $response->assertOk();
        $response->assertViewIs('front::pages.blog');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function blog_detail_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('blog.detail', ['slug' => $slug]));

        $response->assertOk();
        $response->assertViewIs('front::pages.blog-detail');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function blog_filter_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('blog.filter'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function blog_search_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('blog.search'));

        $response->assertOk();
        $response->assertViewIs('front::pages.blog');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function contact_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('contact'));

        $response->assertOk();
        $response->assertViewIs('front::pages.contact');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('home'));

        $response->assertOk();
        $response->assertViewIs('front::index');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function message_store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('contact.store'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function messagestore_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \Modules\Front\Http\Controllers\FrontController::class,
            'messageStore',
            \Modules\Message\Http\Requests\Api\Store::class
        );
    }

    /**
     * @test
     */
    public function product_brand_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('product-brand', ['slug' => $slug]));

        $response->assertOk();
        $response->assertViewIs('front::pages.product-grids');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function product_cat_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('product-cat', ['slug' => $slug]));

        $response->assertOk();
        $response->assertViewIs('front::pages.product-grids');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function product_deal_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('product.deal'));

        $response->assertOk();
        $response->assertViewIs('front::pages.product-grids');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function product_detail_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('product-detail', ['slug' => $slug]));

        $response->assertOk();
        $response->assertViewIs('front::pages.product_detail');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function product_filter_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('shop.filter'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function product_grids_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('product-grids'));

        $response->assertOk();
        $response->assertViewIs('front::pages.product-grids');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function product_lists_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('product-lists'));

        $response->assertOk();
        $response->assertViewIs('front::pages.product-lists');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function product_search_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('product.search'), [
            // TODO: send request data
        ]);

        $response->assertOk();
        $response->assertViewIs('front::pages.product-grids');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('cart.order'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('payment'));

        // TODO: perform additional assertions
    }

    // test cases...
}
