<?php

namespace Tests\Feature\Modules\Shipping\Http\Controllers;

use Tests\TestCase;

/**
 * @see \Modules\Shipping\Http\Controllers\ShippingController
 */
class ShippingControllerTest extends TestCase
{
    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('shippings.create'));

        $response->assertOk();
        $response->assertViewIs('shipping::create');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->delete(route('shippings.destroy', ['shipping' => $shipping]));

        $response->assertRedirect(back());
        $this->assertModelMissing($shipping);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('shippings.edit', ['shipping' => $shipping]));

        $response->assertOk();
        $response->assertViewIs('shipping::edit');
        $response->assertViewHas('shipping');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('shippings.index'));

        $response->assertOk();
        $response->assertViewIs('shipping::index');
        $response->assertViewHas('shippings');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('shippings.store'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('shippings.index'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \Modules\Shipping\Http\Controllers\ShippingController::class,
            'store',
            \Modules\Shipping\Http\Requests\Store::class
        );
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->put(route('shippings.update', ['shipping' => $shipping]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('shippings.index'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_validates_with_a_form_request()
    {
        $this->assertActionUsesFormRequest(
            \Modules\Shipping\Http\Controllers\ShippingController::class,
            'update',
            \Modules\Shipping\Http\Requests\Update::class
        );
    }

    // test cases...
}
