<?php

namespace Tests\Feature\Modules\Message\Http\Controllers\Api;

use Tests\TestCase;

/**
 * @see \Modules\Message\Http\Controllers\Api\MessageController
 */
class MessageControllerTest extends TestCase
{
    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->delete(route('message.destroy', ['message' => $message]));

        $response->assertOk();
        $this->assertModelMissing($message);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('message.index'));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('message.show', ['message' => $message]));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
