<?php

namespace Tests\Feature\Modules\Message\Http\Controllers;

use Tests\TestCase;

/**
 * @see \Modules\Message\Http\Controllers\MessageController
 */
class MessageControllerTest extends TestCase
{
    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->delete(route('messages.destroy', ['message' => $message]));

        $response->assertRedirect(back());
        $this->assertModelMissing($message);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('messages.index'));

        $response->assertOk();
        $response->assertViewIs('backend::message.index');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('messages.show', ['message' => $message]));

        $response->assertOk();
        $response->assertViewIs('backend::message.show');

        // TODO: perform additional assertions
    }

    // test cases...
}
